### ISSUE TITLE
Phase Detection Autofocus

### ISSUE THREAD

**Issue by excllent123** [andrewccchan/andrewccchan.github.io#1]
Hi Andrew：
    Can you share the paper or code relate with PDAF?
    I can' t find this paper Autofocus by Deep Reinforcement Learning   
    or any code related with PDAF

 I have read this paper,  Improving the Reliability of Phase Detection Autofocus    
    ![default](https://user-images.githubusercontent.com/19669013/48399561-f0575f00-e75e-11e8-88a1-ca7cae13f5e1.JPG)
This  matching  curve is  from real-data or simulation?  I have test some case in DualPD sensor,but I can't reproduce this curve,  can you share your experience with me?  you can contact me via E_mail 1161181245@qq.com

Thanks

**Comment by chinchengcsl** [comment]
Hi,

Sorry for the late reply. The abstract version of the paper "Autofocus by
Deep Reinforcement Learning" was accepted by Electronic Imaging 2019, but I
am still preparing for the final version of the paper. So, I am afraid that
I cannot share the paper with you at this moment.
I will send you the paper once the final version is published in the the
proceeding.

Best regards,
Andrew

excllent123 <notifications@github.com> 於 2018年11月13日 週二 下午3:56寫道：
